# Dev-only overrides. Applied automatically by `docker compose`.
services:
  app:
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"

  database:
    ports:
      - "3306:3306"

  mailer:
    ports:
      - "1025:1025"
      - "8025:8025"
