# Dev-only overrides. Applied automatically by `docker compose`.
services:
  app:
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"

  database:
    ports:
      - "3308:3306"

  mailer:
    ports:
      - "1027:1025"
      - "8027:8025"
